spring:
    datasource:
        url: jdbc:mysql://localhost:3306/karyawan-springboot?zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: update
