spring:
    datasource:
        url: jdbc:mysql://localhost:3306/karyawan-springboot?zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 867196689924-r3sv8ovkd2b9n6qo5acv6h4dmreeh1tp.apps.googleusercontent.com
                        clientSecret: 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
                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - email
                            - profile
                
app:
    auth:
        tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
        tokenExpirationMsec: 864000000
    cors:
        allowedOrigins: http://localhost:3000
    oauth2:
        authorizedRedirectUris:
            - http://localhost:3000/oauth2/redirect
